Added html semantic structure
Troyasha/otus-css-troyanovskaya pull request #1
Opened 2023-01-28 22:37 UTC by Troyasha

2023-01-31 17:03 UTC, lipa88-mk requested changes
Очень хорошо, но можно бы еще убрать лишние секции, немного поправить теги по смыслу и, самое главное, проверить структуру страницы по заголовкам

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +        <section>
Вторая секция тут скорее лишняя, одной достаточно

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +        <h2>
Если это заголовок этой секции, то в разметке он должен быть в начале. Далее с помощью стилей его уже переставим согласно макету

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +            <div>__</div>
Это декоративное, это лишнее)

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +    <section>
В целом тут, выше и далее одной секции достаточно, вторую по вложенности я бы убрала

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +            <h4>JESS WONDER </h4>
Почему заголовок 4 уровня? К какому заголовку 3 уровня он относится? Думаю, тут еще стоит подумать над иерархией заголовков.

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +            </span>
Спан - хорошо, но лучше блочный тег, хотя бы параграф. И это скорее 2 отдельных параграфов, без бр, тк строчк можно переставить местами

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +            <h3>Designers</h3>
Точно так же, почему уровень 3? Это дизайнеры студии, те скорее заголовок 2

2023-01-31 17:03 UTC, lipa88-mk commented on index.html
> +            <aside>
Это не асайд, это отзывы компаний об этой студии

2023-02-02 17:22 UTC, Troyasha commented on index.html
> +            <h4>JESS WONDER </h4>
Исправлен на h3. Надеюсь, поняла верно.

2023-02-02 17:23 UTC, Troyasha commented on index.html
> +            <aside>
Поменяла на список.

2023-02-08 18:45 UTC, merged